### ISSUE TITLE
As a game master, I don't want users to cheat

### ISSUE THREAD

**Issue by Steppico** [Steppico/a-maze-ing#20]
It is easy to complete the game by ...navigating the arrow around the maze. This "kind of" defies the meaning of the experience though (although users can still have a feeling of what it means to think logically).

As a game master, I want to introduce a way to block the arrow from doing so.

Here are some options we can decide to use to solve it, but I am open to discuss others if you have any in mind:

1. Invisible walls
    The arrow won't be able to go forward if turned right or left at the start;
2. Coins
    _Incentivate_ the user doing the right thing: for instance, collecting a coin in the middle of the maze;
3. Instructions
    Giving clear instructions on what to do, and simply trust the user.

**Comment by Steppico** [comment]
I've been thinking, is this really necessary? Honestly it doesn't really change the experience that much: users will still need to use the game's logic to _cheat_ and not traversing the maze.

What do you think, @zero4994 ?

**Comment by zero4994** [comment]
I think we could do 2 things first is to set `clear` instructions on how to use the game, but leaving the possibility of "cheating". This is useful in 2 ways: 

1. Users can quite literally think out of the box 🤣
2. I think for users that do "cheat" it shows them that usually there is more than just one way of solving a problem without defeating the purpose of thinking logically.

Actually I think that this should remain as is and when presenting the game showing both solutions to point out no.2

Note: I use cheating for a lack of a better word, I think its not

**Comment by Steppico** [comment]
Sorry for the late reply! I believe you're right, that is the approach that makes more sense.
I'll proceed inserting clear instructions, and finally we'll let them decide for themselves.

Thinking about it, this would also help identify the out-of-the-box thinkers, which is **_noice_**!
